# Generated by Django 5.0.6 on 2024-07-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vid',
            new_name='pid',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('process', 'Processing'), ('shipped', 'Shipped')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('disabled', 'Shipped'), ('draft', 'Processing'), ('rejected', 'Delivered')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('disabled', 'Shipped'), ('draft', 'Processing'), ('rejected', 'Delivered')], default=None),
        ),
    ]
